### ISSUE TITLE
No Hitstun

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#10]
###### Description
-When Overcharged, Bug Zapper is not doing AoE hitsun.

###### Steps to reproduce
-Overcharge Bug Zapper and hit normal AoE targets with it.

###### Version
-Main (just now I noticed this is to clarify the DST Version, not our version).

**Comment by AtobaAzul** [comment]
It was only doing hitstun for spiders, fixed indev.
