### ISSUE TITLE
Wixie Crash with Snap Traps... Yes... Again...

### ISSUE THREAD

**Issue by ShyNuke** [AtobaAzul/UncompromisingMode#102]
###### Description
-This one wasn't fixed from the previous one: if Wixie Panic attacks a Snap Trap, it will crash the game.

###### Version
-UM GIT and DST Live.

![image](https://user-images.githubusercontent.com/131507193/235600972-cd6115ae-d923-4b4c-b84f-6ac09607a182.png)

**Comment by AtobaAzul** [comment]
Please provide the full log, I have no idea where this crash is actually happening.
