### ISSUE TITLE
Probably for the better, but Bunnyman seem to be bugged!

### ISSUE THREAD

**Issue by ShyNuke** [AtobaAzul/UncompromisingMode#105]
###### Description
-"BUNNYMAN_RESPAWN_TIME_DAYS = 3' this is on the code, but isn't happening at all, Bunnyman are respawning each 1 day! Sincerely, let it this way, or buff the hell out of them, because they are in a bad spot now even with the bug...

###### Version
-UM GIT and DST Live.

**Comment by AtobaAzul** [comment]
Working as intended.
