### ISSUE TITLE
Portal with wrong cost?

### ISSUE THREAD

**Issue by ShyNuke** [AtobaAzul/UncompromisingMode#106]
###### Description
-"RECIPE_CELESTIAL_UPGRADE_GLASS_COST = 20", might be understanding this wrong, but this is Glass for the Celestial Portal, right? If so, the cost right now is 5, not 20!

###### Version
-GIT UM, DST Live.

**Comment by AtobaAzul** [comment]
Unused variable. Not sure why it even is a thing.
