### ISSUE TITLE
Sludge Lingering Damage

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#11]
###### Description
-The Lingering damage of the Sludge Cannonball doesn't seem to be working proprelly.

###### Steps to reproduce
-Shoot the cannon and boat to that place, nothing will happen with your boat.

###### Version
Main.

**Comment by AtobaAzul** [comment]
Boat damage doesn't properly work because the radius of the damage is smaller than the boat's size. I've increased the radius in the dev build.
