### ISSUE TITLE
IA + UM

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#12]
###### Description
-UM related stuff are not being generated in IA, both in UM's Beta and UM's Live.

###### Steps to reproduce
-I haven't changed any config, it was suppose to generate regardless, since some patches ago it was made so it generated without any changes in configs.

###### Version
Main.

**Comment by AtobaAzul** [comment]
Fixed in [7023a32](https://github.com/AtobaAzul/UncompromisingMode/commit/7023a32b1286dc50ef0a0d49dca2c006cfd338ee)

Hooded forest probably generates in the volcano again though. Decided that isn't really a problem anyways since you can't access it normally.
