### ISSUE TITLE
Roship damage right now is pretty bad.

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#123]
###### Description
-Roship damage is completely broken, it's doing 20 with or without electrical protection, only diminishes if you have armor). As a side note, the stagger on him is working fine, no protection, longer stagger, protection, shorter stagger.

###### Version
-UM Live, DST Beta.

**Comment by AtobaAzul** [comment]
Fixed. I think. You did, right?
