### ISSUE TITLE
Game crashed when trying to cook with cooked durian 

### ISSUE THREAD

**Issue by GaopoHuang** [AtobaAzul/UncompromisingMode#127]
###### Description
*Describe what happend*
The game crashed with forced disconnection when a crockpot food is cooked

###### Steps to reproduce
*Explain how the bug happened and how did you make it happen*
When trying to add a cooked durian with a twig into a crock pot food, the game disconnects when "cook" button is clicked. 
This seems to happen only if a cooked durian is used and the food cannot be made into "stuffed peeper poppers". If the stuffed peeper poppers requirement is satisfied, the food can be made successfully.

###### Version
*If applicable, what DST version were you on? (Main or beta)
Main

###### Logs
*Nescesary when reporting crashes. Logs can be found at Documents\Klei\DoNotStarveTogether*
<sup>IF YOU DO NOT PROVIDE A LOG WHEN REPORTING A CRASH WE'LL BE RATHER DISSAPOINTED</sup>
Here is a screenshot of the game before the crash, along with the crash log.
![image](https://github.com/AtobaAzul/UncompromisingMode/assets/44309248/4a3754e5-2df7-452a-859b-da08221316e0)
[master_server_log.txt](https://github.com/AtobaAzul/UncompromisingMode/files/12093281/master_server_log.txt)

**Comment by AtobaAzul** [comment]
Thanks for the report! Fixed in [4c9785b](https://github.com/AtobaAzul/UncompromisingMode/commit/4c9785b7419f59cd7f81c53d9889664670ea5bc5)
