### ISSUE TITLE
Normal Pig Guards

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#13]
###### Description
-Not talking about UM's Pig King Pig Guards, talking about the normal ones that you would have in Vanilla. Those are right now really buggy, they never return to their totems if there is a person nearby them, they walk a little and reeaggro to you if you are close enoug + their walk is strange, they walk a little, tweak, walk a little, tweak...

###### Steps to reproduce
-Just face any Pig Guard that is not the UM ones.

###### Version
-Main for DST, Beta for UM.

**Comment by AtobaAzul** [comment]
Fixed sometime ago.
