### ISSUE TITLE
Wixie is uncomfortable with everything!

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#135]
###### Description
-Wixie is announcing if she is having Armor that increases her Phobia whenever you equip something, even if that something isn't increasing her Phobia.

###### Steps to reproduce
-Have a Log Suit, and equip a Sligshot to her.

###### Version
-Main DST, Main UM.

**Comment by Shodance** [comment]
My code was stupid and dumb, fixed it in dev, will patch later0
