### ISSUE TITLE
Dimvae

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#14]
###### Description
-Dimvae are being capable of spawning on water, this makes them walk on water, like you would if you had God Mode Enabled.

###### Steps to reproduce
-Just be in a boat an equip Scale Mail.

###### Version
Main DST, Beta UM.

**Comment by AtobaAzul** [comment]
Fixed in [bc72578](https://github.com/AtobaAzul/UncompromisingMode/commit/bc725784297b57700ced62f039286c1589ce5a45)
