### ISSUE TITLE
Crash with Chimp RNE

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#15]
###### Description
-Game crashed once an RNE started, it was the Chimp Random Event, not sure if it's just the chimp event tho...

###### Steps to reproduce
-Just wait for night.

###### Version
-Beta DST, Beta UM.

###### Logs
-Sended in a print in Beta Bug Reports.

**Comment by Shodance** [comment]
Patched this in the latest beta update, no more crash!
