### ISSUE TITLE
Treeguard Spamming Pinelings

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#16]
###### Description
-Treeguards are spamming pinelings, even if there is no stump to transform around, they just keep stomping the ground.

###### Steps to reproduce
-Fight a treeguard that spawned from trees.

###### Version
-Beta DST, Beta UM.

**Comment by AtobaAzul** [comment]
Fixed in [bc72578](https://github.com/AtobaAzul/UncompromisingMode/commit/bc725784297b57700ced62f039286c1589ce5a45)

**Comment by AtobaAzul** [comment]
Shit, wrong issue lmao

**Comment by AtobaAzul** [comment]
Fixed indev, coming soon to live.
