### ISSUE TITLE
Twins Laser

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#17]
###### Description
-If Orange is floating above water and does the laser, nothing happens (kinda of a bug for a long time, might be okay this way but whatever).

###### Steps to reproduce
-Make him go in water and do the laser.

###### Version
-Beta UM and Beta DST (Sure it works in Live UM and Live DST as well).

**Comment by AtobaAzul** [comment]
Fixed - but let it be known I didn't change the fx on water just yet.
