### ISSUE TITLE
Lunar Grimoire Interactions

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#19]
###### Description
-Lunar Grimoire is not transforming Pigs into Werepigs (Any type of Pig). It's also not refiiling the meter of Woodie and not making Woodie transform past one transformation. + there is no tip.

###### Steps to reproduce
-Use Lunar Grimoire in those things.

###### Version
-Beta UM, Beta DST.

**Comment by AtobaAzul** [comment]
Fixed in the gitlab dev version.
