### ISSUE TITLE
C.K. Bugs - Waves

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#20]
###### Description
-After deactivating if you go away, C.K. will sometimes create waves even if "sleeping".

###### Steps to reproduce
-Trigger him, make him go to sleep and try to wake him up again, he will make some waves (not sure if it's 100% of the time).

###### Version
-Beta DST, Beta UM.

**Comment by AtobaAzul** [comment]
This bug was fixed already - Was this before v2.0.4.1?
