### ISSUE TITLE
C.K. Bugs - Trident doing AoE?

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#21]
###### Description
-For some reason, Trident kills birds that are close to the main target, but it's not suppose to have AoE.

###### Steps to reproduce
-Keep killing anything until a wild bird appears, the Trident will kill it.

###### Version
-Beta UM, Beta DST.

**Comment by AtobaAzul** [comment]
Unable to reproduce.

https://user-images.githubusercontent.com/94794129/223487677-81ddee6e-5a1e-41b0-84cc-ede92c2baed6.mp4
