### ISSUE TITLE
C.K. Bugs - Trident last use, Klei or UM?

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#22]
###### Description
-Not sure if it's UM or Vanilla: when you use Trident with the last use in water for the Big Geysers, it won't spawn Geysers and it will break.

###### Steps to reproduce
-Have it at one use and do the geysers.

###### Version
-UM Beta. DST Beta.

**Comment by AtobaAzul** [comment]
Apparently a UM issue, however, I have no idea what makes Klei's work and ours not.
Klei
![image](https://user-images.githubusercontent.com/94794129/223486275-ad26cc33-e170-443a-bc15-48adaad024e6.png)

Us
![image](https://user-images.githubusercontent.com/94794129/223486380-99ad9811-c510-4c30-88c5-2a096c3f33a2.png)
