### ISSUE TITLE
BQ Blockers

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#23]
###### Description
-Whenever BQ spawns Blockers Grumble, the game crash.

###### Steps to reproduce
-Just spawn a Blocker Grumble yourself or let BQ do it

###### Version
-Beta UM, Beta DST.

###### Logs
-Coudn't get the log, will try to send a image of it in Beta Bug Reports.

**Comment by AtobaAzul** [comment]
**_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA_**






Fixed.
