### ISSUE TITLE
C.K. Crash with Moon Beacon

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#25]
###### Description
-C.K. crashes when it drops the chest for Moon Beacon.

###### Steps to reproduce
-Just kill C.K. with the Moon Beacon being guaranteed.

###### Version
-DST Beta, UM Beta.

Log:
 
[Crash.txt](https://github.com/AtobaAzul/UncompromisingMode/files/10934603/Crash.txt)

**Comment by AtobaAzul** [comment]
Fix coming on the update's release AAA
