### ISSUE TITLE
Matilda doing crazy damage

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#29]
###### Description
-As it's now, matilda is powering up it's shoots when charging it, with was not suppose to be a thing, from what I understand. (Gold ammo, for example, is dealing 3 imes 59.5, not 3 times 51).

###### Version
-DST Beta, UM Live.

**Comment by AtobaAzul** [comment]
Considering this hasn't been changed in nearly 4 months, I'll say that that is, in fact, intentional.
