### ISSUE TITLE
Wiltfly Cheese

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#30]
###### Description
-If you go to the ocean when Wiltfly is spawning, she will not spawn and will also not spawn during the whole summer, only spawning at the beggining of the next. You can then do this again at the beggining of next summer to fix it, and then do this cheese again.

###### Version
-DST Beta, UM Live.

**Comment by Shodance** [comment]
By the way I think this works for literally every boss, because Klei didn't feel like figuring out how to not make boat mechanics break the game.

**Comment by AtobaAzul** [comment]
I'm not sure we can do that either because the ocean appears to have the "nohassler" tag - making Dfly ignore that or removing that tag could have unforseen consequences.

**Comment by AtobaAzul** [comment]
Actually, there's something I think I can do here.

**Comment by AtobaAzul** [comment]
Fixed.
