### ISSUE TITLE
Hibees Queen Broken in UM

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#35]
###### Description
-Just including this in here as a reminder of it really: Hibees Queen is pretty broken in UM... She despawns because she doesn't detect herself, she despawns really easily thanks to her arena being really small and her attacks being too big, she spams way too many Grumbles at last two phases...

###### Version
-Live UM, Live DST.

**Comment by AtobaAzul** [comment]
(We did not fix the gameplay portion of it, just her despawning immediatly.)
