### ISSUE TITLE
Don't run Wathom, Don't!

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#37]
###### Description
-Wathom running looks dummy with Shield of Terror, he also becomes invisible while mounted on Beefs.

###### Version
-Live UM, Live DST.

**Comment by AtobaAzul** [comment]
Nothing we can realistically do with the shield, lantern and possibly other items having problems like that.
Fixed in [4437602](https://github.com/AtobaAzul/UncompromisingMode/commit/443760229b1ed065a40581caea1cd2b3a461b952)
