### ISSUE TITLE
Wathom really don't like Beefalos

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#38]
###### Description
-Wathom will make the range of Beefalos bugged when attacing with his "increased Range". If you try to attack something with a Beefalo, the Beefalo will account for Wathom's range with his leap, so the Beefalo will just attack the air in front of him.

###### Version
-Live UM, Live DST.

**Comment by AtobaAzul** [comment]
Fixed in [f85e858](https://github.com/AtobaAzul/UncompromisingMode/commit/f85e8584a5f9947147271f648206e726d74e53df)
