### ISSUE TITLE
Winona Hunger Drain with Beefalos

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#39]
###### Description
-When mounted on a Beefalo, Winona gains nothing of her perks, but will still lose hunger on actions.

###### Version
-Live DST, Live UM.

**Comment by AtobaAzul** [comment]
fixed in [a6555c1](https://github.com/AtobaAzul/UncompromisingMode/commit/a6555c12f7054c4b4ea1b19f8fb647aba023df60)
