### ISSUE TITLE
Wicker Mini Rework

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#40]
###### Description
-Lunar Grimoire and Apicultural Notes are lacking tips. Also, Lunar Grimoire is not refreshing Woodie Transformation Meter (I tested it with a created char, maybe it works if it's a player...?)

###### Version
-Live UM, Live DST.

**Comment by AtobaAzul** [comment]
I'm 99% sure I fixed the refreshing and retransforming issue.

**Comment by AtobaAzul** [comment]
Fixed.
