### ISSUE TITLE
Deerclops and Trepidation "ramification" attacks with pushes.

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#43]
###### Description
-Some attacks make mobs look like they shoudn't be capable of being pushed, but they do: Auraclops Big Attack, Trepidation when he spawns Tentacles.

###### Version
-Live DST, Live UM.

**Comment by AtobaAzul** [comment]
Fixed in [48d130f](https://github.com/AtobaAzul/UncompromisingMode/commit/48d130f429633d14bb2054f582102e72ff5e3c9d)
