### ISSUE TITLE
Lag Comp

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#44]
###### Description
-Wixie is pretty much unplayable with it (right now this is getting solved by quite literally turning it off), Shadow Vortex also (It also just turn Lag Comp off, and it doesn't put it on afterwards, from what I tested), Wathom attack looks odd (Passable tho) and the thing from the puzzle looks REALLY off (Probably better to give a big warning about it in somewhere notable, while it isn't fixed/if it will be fixed).

###### Version
-Live UM, Beta UM.

**Comment by AtobaAzul** [comment]
(God help our souls.)

**Comment by AtobaAzul** [comment]
I don't think we can do much about wixie. 
Shadow Vortex turns lag comp on when it turns day.
For Wathom, I did all I could. 
If the thing from the puzzle you mean is the warbles, those work fine.
Walter thing (mentioned in the original description) I fixed, I know the IA devs had issues with something related.
I've put a warning in the steam page.
