### ISSUE TITLE
Mod Incompatibility with Feast and Famine

### ISSUE THREAD

**Issue by MagmaticSpirit** [AtobaAzul/UncompromisingMode#49]
###### Description
Feeding Monster Meats to birds without Monstrous Eggs from Feast and Famine on in their config menu produces regular eggs

###### Steps to reproduce
Turn OFF Monstrous Eggs in Feast and Famine, but keep Monster Eggs ON in UM
Feed Bird with monster morsel/meat
notice regular eggs pop out
feast with no famine

###### Version
Main

**Comment by MagmaticSpirit** [comment]
Note: Turning Monstrous Eggs on and Monster Eggs off produces Monstrous Eggs properly, UM's Monster Eggs seem to be completely unable to spawn however.

**Comment by AtobaAzul** [comment]
Feast & Famine is likely overriding the function. Nothing I can do from our end.

**Comment by AtobaAzul** [comment]
(Reopening because I closed with the wrong type)
