### ISSUE TITLE
Wilson transmuting Monster Meat

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#53]
###### Description
-This option is not appearing at the moment in Wilson's Char Tab, only if you search for it. Also: the note in the skill tree doesnt show one of the transmutations.

###### Version
-Live UM, Live DST.

**Comment by AtobaAzul** [comment]
For the skill tree text, max lines limitation. can't do much.
Recipe stuff has been fixed.
