### ISSUE TITLE
Winona's G.E.Merator Fully Charged

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#57]
###### Description
-Winona's G.E.M.enator's comes build fully charged when you craft it, it's charged even tho it has no visual on the ground for it. Also, after reloading the server, the Normal Generator looks like it's at low charges.

###### Version
-Git UM, Live DST.

![image](https://user-images.githubusercontent.com/123885681/230467037-c97129e1-8563-4dad-a089-f27d3ea81a7c.png)

**Comment by AtobaAzul** [comment]
Fixed in [3e4bdd9](https://github.com/AtobaAzul/UncompromisingMode/commit/3e4bdd9c2a54b10058f5fd9a483d82b3eb559cde)
