### ISSUE TITLE
Slurtle/Snurtle Drops

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#59]
###### Description
-Slurtles/Snurtles drops are bugged at the moment:

>Sometimes the sound effect of breaking appears even tho you get the armor (In Vanilla, it's only when you don't get the armor, or to put it better, when you get Broken Shells)
>Sometimes they will only drop Slime, with shoudn't be a thing, they should always drop either the armor or the Broken Shell.

###### Version
-Git UM, Live DST.

**Comment by AtobaAzul** [comment]
I genuienly have no idea why and how this happens. I tried putting the AddIfNotChanceLoot("slurtle_shellpieces") and the related event listener but it did nothing. It's not something critical so I'll just close it as not planned, seeing as there's no solution I could think of.
