### ISSUE TITLE
Snowpiles Crash with Rain

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#60]
###### Description
-Snowpiles are crashing with rain.

###### Version
-Git UM, Live DST.
![image](https://user-images.githubusercontent.com/123885681/230477428-076377c8-a406-476e-b3dd-60a743064bf7.png)

**Comment by AtobaAzul** [comment]
Fixed in [0b3526c](https://github.com/AtobaAzul/UncompromisingMode/commit/0b3526cb0c582e73c8d8a5bd6e92f8c90dd02a85)
