### ISSUE TITLE
UM Skins

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#62]
###### Description
-Skins are not appearing correctly in the equipped slots, Cursed Antler and Ancient Amulet in specific (The Frock art also is kinda strange...?).

###### Version
-GIT UM, Live DST.

**Comment by AtobaAzul** [comment]
Fixed in [02f9e4f](https://github.com/AtobaAzul/UncompromisingMode/commit/02f9e4fd6f562a0ca0bdc962e68aae9f200f3ca9) and [4b8dbb2](https://github.com/AtobaAzul/UncompromisingMode/commit/4b8dbb23417eca44ecebe7474bcb29cffa30c6ac)
