### ISSUE TITLE
Config Changes

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#64]
###### Description
-When the Config for Harder Pigs is enabled, the physics when you hammer a Pig House or a Bunny Hut don't exist (That little shake that happens everytime you hammer it).

-When the Config for Harder Pigs is off, Bunnys also will be affected, they don't get crunky when you hammer down one of their huts.

-When Willow Config is disabled, you still get Willows new Portrait.

###### Version
-Git UM, Beta DST.

**Comment by AtobaAzul** [comment]
Fixed first one in gitlab, Second and Third one are working as intended.
