### ISSUE TITLE
Generator Animation

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#65]
###### Description
-The Normal Generator does an animatio of "charging" when put in the ground, but then, if you don't have it at 100%, it soon after will show the correct amount. Not something big, but one of those little details that make it not look lazy and stuff.

###### Version
-Git UM, Beta DST.

**Comment by AtobaAzul** [comment]
There isn't much I can do without making an entirely new animation.
