### ISSUE TITLE
Lesser Life Amulet Cooldown is for everyone

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#66]
###### Description
Lesser Life Amulet Cooldown is happening for everyone, intended?

###### Version
-Git UM, Beta DST.

**Comment by AtobaAzul** [comment]
Fixed in [65f20fd](https://github.com/AtobaAzul/UncompromisingMode/commit/65f20fd9b31d45b02e739c7c27f28e82274cd11e)
