### ISSUE TITLE
Cookie Cutter Cap + Companions

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#67]
###### Description
-Cookie Cutter Cap is still hitting companions, and taking domestication out of Beefs.

###### Version
-Git UM, Beta DST.

**Comment by AtobaAzul** [comment]
Properly fixed in [4c2d645](https://github.com/AtobaAzul/UncompromisingMode/commit/4c2d645bb8a62f2fb7b44cc0394817523a172ea6)
