### ISSUE TITLE
C.K. Wave attack

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#68]
###### Description
-If C.K. starts charging his waves, NOTHING will stop them from appearing, even death.

###### Version
-Git UM, Beta DST.

**Comment by AtobaAzul** [comment]
Fixed in [4c2d645](https://github.com/AtobaAzul/UncompromisingMode/commit/4c2d645bb8a62f2fb7b44cc0394817523a172ea6)
