### ISSUE TITLE
crashed upon trying to host a world 

### ISSUE THREAD

**Issue by 42stinger** [AtobaAzul/UncompromisingMode#7]
###### Description
upon trying to host a world it would wait a second before saying 
<img width="1131" alt="Capture dont starve" src="https://user-images.githubusercontent.com/50055184/219531997-9da54786-4a54-4e24-8468-eecb4455f40d.PNG">

###### Steps to reproduce
crashed upon trying to host a world 

###### Version
*If applicable, what DST version were you on? (Main or beta)
I was on main

###### Logs
[dont starve together data logs.zip](https://github.com/AtobaAzul/UncompromisingMode/files/10762553/dont.starve.together.data.logs.zip)

**Comment by AtobaAzul** [comment]
It would seem you're missing a file (postinit/components/components/combat_replica.lua)

Try reinstalling the mod.
