### ISSUE TITLE
Woby is REALLY scared of Bunnys...

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#70]
###### Description
-If you command Woby to bark at a bunny, the bunny will be affected in nothing, but Woby will start running away from it, hiding in fear and ignoring commands while in the presence of the mighty bunny (Definely works with similars as well).

###### Version
-Git UM, Beta DST.

**Comment by Shodance** [comment]
Marking as fixed in dev.
