### ISSUE TITLE
UM Skins

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#71]
###### Description
-UM skins are broken again, I can't change them with Clean Sweeper.

###### Version
-GIT UM, BETA DST.

**Comment by AtobaAzul** [comment]
Do you have modded skins API enabled?

**Comment by ShyNuke3D** [comment]
I forgor, gonna test the fix with it now!

**Comment by ShyNuke3D** [comment]
Everything working fine, my bad!
