### ISSUE TITLE
c_um_findets()

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#76]
###### Description
-This command seems to not be working, or I am dumb, I give it a 50/50.

###### Version
-GIT UM, DST Beta.

**Comment by AtobaAzul** [comment]
Working fine here.
![image](https://user-images.githubusercontent.com/94794129/233388364-041b5850-88c1-4a9b-b53d-97cd1718c203.png)
![image](https://user-images.githubusercontent.com/94794129/233388399-bb10afd3-4989-41b2-91d2-7a1d9f248971.png)
