### ISSUE TITLE
Moonmaw not spawning second wave of Crystalized Lavaes

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#78]
###### Description
-When Moonmaw hits the ground to summon the fallen Crystals attack at half health, she isn't spawning the Crystalized Lavaes that she should be spawning, making the fight have only 1 Crystal Phase.

###### Version
-GIT UM, Live DST.

**Comment by Shodance** [comment]
Marked as fixed in dev
