### ISSUE TITLE
Trepidation Fix

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#8]
###### Description
-Trepidation is now working differently, there is now no more reason for him to be untargetable with "F" or "CTRL + F" when above 50% sanity.

###### Steps to reproduce
-Just find him when he is aggroing and be above 50% sanity, you need to hit him with your mouse (and not even once, but for the entire fight).

###### Version
-Beta.

**Comment by AtobaAzul** [comment]
Done.
