### ISSUE TITLE
Frigid Crow Trading

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#81]
###### Description
-Game Crash when you try to give a mob Frigid Crown.

###### Version
-Live UM, Live DST.

![image](https://user-images.githubusercontent.com/123885681/233086048-72d662fa-3798-4e9c-91c4-56ea3b7c3894.png)

**Comment by AtobaAzul** [comment]
Attempted fix in [81e71e3](https://github.com/AtobaAzul/UncompromisingMode/commit/81e71e3dc1bb2d08c9724e2e07f0c6e485b64f7a)
