### ISSUE TITLE
Stick-a-Rounds not flexible

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#82]
###### Description
-If you're at Vanilla, you can only make Stick-a-Rounds with Sludge, if you're at IA, only with Tar. It's a minor thing, but if you bring stuff over from the other "dimension" when you're playing with both in a dedicated server, that affects it + all other tar stuff is working with that, just not this one.

###### Version
-Live UM, Live DTS.

**Comment by AtobaAzul** [comment]
The RecipePostinit that would've made them interchangeable simply stopped working. This current method ensures you can craft them with tar and sludge, unlike the previous version.

**Comment by AtobaAzul** [comment]
Can't/Won't fix.
