### ISSUE TITLE
Deconstructing Shard Scale

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#83]
###### Description
-Using Deconstruct Staff in Shard Scale gives you back only 2 Infused Moon Shard.

###### Version
-Live DST, Live UM.

**Comment by AtobaAzul** [comment]
![image](https://user-images.githubusercontent.com/94794129/233388801-4f588355-4b42-4093-8843-2d994197bbad.png)
Unable to reproduce.
