### ISSUE TITLE
Salt Piles getting removed upon season change

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#84]
###### Description
-Some Dev told before that the idea of the Salt Shaker was prepping your base before the Winter hits for Snowpiles; however, as it's now, Salt Piles get removed upon the change of Autumn to Winter.

###### Version
-Live DST, Live UM.

**Comment by AtobaAzul** [comment]
Fixed in [b114d17](https://github.com/AtobaAzul/UncompromisingMode/commit/b114d17b3e4b7c933008ee5d7983d6f25ae71ec2)
