### ISSUE TITLE
Wathom + Life Giving Amulet

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#87]
###### Description
-Could be intended, but to be sure: the cooldown for Life Giving Amulet goes off even if you don't become Shadow Wathom while dying and reviving with Wathom.

###### Version
-Main DTS, Main UM.

**Comment by AtobaAzul** [comment]
Working as intended because I *hate wathom!!* /s

**Comment by AtobaAzul** [comment]
Working as intended.
