### ISSUE TITLE
Mossy Forest Turf

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#88]
###### Description
-Hooded Forest Turf icon in the ground is different from the icon on inventory and on craft menu. Also, the patch notes says it should have inspect lines, at least for Wilson, it says the generic "It's a... Thing."

###### Version
-Main DST, Main UM.

**Comment by AtobaAzul** [comment]
I _THINK_ that was fixed. Feel free to reopen thge issue if otherwise, I don't feel like testing.
