### ISSUE TITLE
Salt Piles are eternal

### ISSUE THREAD

**Issue by ShyNuke3D** [AtobaAzul/UncompromisingMode#91]
###### Description
-I passed about a year and they are still there, was the season change the only method of it going away? If so, probably good to implement the to them as Snowpiles? Get removed by rain?

###### Version
-Main DST, GIT UM.

**Comment by AtobaAzul** [comment]
The technically spoil after 20 days iirc - odd that that isnt working

**Comment by ShyNuke3D** [comment]
It isn't working for skipping with TMI, should I try a long test to see if it's true without it?

**Comment by ShyNuke3D** [comment]
Yep, they are Eternal, stayed looking at them for 30 days straight, still here

**Comment by AtobaAzul** [comment]
They stayed for 40. Made them dissapear under rain outside of winter and halvedtheir spoil time to be 20.
