### ISSUE TITLE
Wixie has a Crippling Fear of Snap Traps

### ISSUE THREAD

**Issue by ShyNuke** [AtobaAzul/UncompromisingMode#97]
###### Description
-Snap Traps (the ones you make in this case) seem to be making Wixie nervos... Also, I think I also got a crash with a Snap Trap breaking with Wixie Panic Attack.

###### Version
-GIT UM and Live DST.

![image](https://user-images.githubusercontent.com/131507193/235317120-83ada4f8-431f-47fa-9d49-2accc639a675.png)

**Comment by Shodance** [comment]
Marking as fixed in dev.
