### ISSUE TITLE
A number of Crashes with Mannequin and UM stuff

### ISSUE THREAD

**Issue by ShyNuke** [AtobaAzul/UncompromisingMode#98]
###### Description

Items that make the game crash when you equip the mannequin with:

-Broken Toy

-Scalemail

-Cat Eye-Goggles (Doesn't Crash the game, but makes the head of the mannequin invisible)

-Feather Frock (Including Skin)

-Gore Horn (The "bug" in this one is that he can actually wear it, but when you try to unequip it crashes, it happens even if you're Vet Cursed)

-Red Gem Armor from C.K.

And that is it, Shadow Crow is working fine, I saw in there they commented that it was crashing. They probably equipped it at the same time with Frock.

Note: Floral + Hibernation Vest are lacking Tips!

###### Version
-GIT UM and Live DST

![image](https://user-images.githubusercontent.com/131507193/235316097-e97997b7-6c6c-4623-b107-4aa70d116eb3.png)
![image](https://user-images.githubusercontent.com/131507193/235317484-78c98992-3f31-44a8-9b35-1e29e56ad7b4.png)
![image](https://user-images.githubusercontent.com/131507193/235317971-ced6b769-9af4-47ae-97e5-91d76b106477.png)
![image](https://user-images.githubusercontent.com/131507193/235317991-47232c2f-5073-4550-92b7-2245f6bb43ae.png)
![image](https://user-images.githubusercontent.com/131507193/235320935-6223c2cf-9dcd-40b4-b2a7-88095f92b8bf.png)
![image](https://user-images.githubusercontent.com/131507193/235321267-762a572e-1500-49c5-9d6e-69d731e01dcd.png)
![image](https://user-images.githubusercontent.com/131507193/235321281-70b21c16-2138-499f-879a-d0beb96858c8.png)
![image](https://user-images.githubusercontent.com/131507193/235321600-b8c808ee-ec55-41e9-9eaf-f0de98641ff0.png)

**Comment by Shodance** [comment]
Marking as fixed in dev.

Hibearnation Vest needs a tip? I don't think it's missing one?
